name: key-vault

services:
  api:
    container_name: backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ./entrypoint.sh
  db:
    container_name: postgresql
    image: postgres:17
    restart: always
    env_file:
      - ../.env
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../.env
    ports:
      - 15432:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
